arch:
  - amd64
  - ppc64le
language: node_js
sudo: false
#updated latest node_js versions & Removed old versions 4,6,8
node_js:
  - "15"
  - "node" 
notifications:
  email: false
cache:
  directories:
    - $HOME/.npm
    - node_modules
